### ISSUE TITLE
op-geth stuck here. run full node with the snapshot

### ISSUE THREAD

**Issue by tpkeeper** [superseed-xyz/node#20]
```
INFO [04-29|05:21:45.877] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors= vhosts=*
INFO [04-29|05:21:45.877] WebSocket enabled                        url=ws://[::]:8546
INFO [04-29|05:21:45.877] WebSocket enabled                        url=ws://[::]:8551
INFO [04-29|05:21:45.877] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=localhost
INFO [04-29|05:21:46.865] Unindexing transactions                  blocks=170,502 txs=170,502 total=5,769,801 elapsed=1.000s
INFO [04-29|05:21:52.935] Generated state snapshot                 accounts=4707 slots=38106 storage=3.31MiB dangling=0 elapsed=7.071s
INFO [04-29|05:21:54.865] Unindexing transactions                  blocks=1,471,228 txs=1,471,253 total=5,769,801 elapsed=9.000s
INFO [04-29|05:22:02.867] Unindexing transactions                  blocks=2,770,000 txs=2,770,201 total=5,769,801 elapsed=17.001s
INFO [04-29|05:22:10.867] Unindexing transactions                  blocks=4,037,839 txs=4,038,607 total=5,769,801 elapsed=25.002s
INFO [04-29|05:22:18.868] Unindexing transactions                  blocks=5,299,000 txs=5,300,948 total=5,769,801 elapsed=33.003s

```

```
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101500.1 # version sourced 
    container_name: superseed-op-geth
    environment:
      GETH_ROLLUP_DISABLETXPOOLGOSSIP: "false"
      GETH_ROLLUP_SEQUENCERHTTP: "https://mainnet.superseed.xyz"
      GETH_VERBOSITY: "3"
      GETH_DATADIR: "/data"
      GETH_HTTP: "true"
      GETH_HTTP_ADDR: "0.0.0.0"
      GETH_HTTP_API: "web3,debug,eth,txpool,net,engine"
      GETH_HTTP_VHOSTS: "*"
      GETH_WS: "true"
      GETH_WS_ADDR: "0.0.0.0"
      GETH_WS_API: "web3,debug,eth,txpool,net,engine"
      GETH_AUTHRPC_ADDR: "0.0.0.0"
      GETH_AUTHRPC_PORT: "8551"
      GETH_AUTHRPC_JWTSECRET: "/jwt.txt"
      GETH_RPC_BATCH_REQUEST_LIMIT: "99999999"
      GETH_RPC_BATCH_RESPONSE_MAX_SIZE: "999999999999999"
      GETH_SYNCMODE: "full"
      GETH_NODISCOVER: "true" # sourced from superseed
      GETH_OVERRIDE_HOLOCENE: "1736445601" # sourced from superseed
      GETH_OVERRIDE_GRANITE: "1726185601" # sourced from superseed
      GETH_ROLLUP_HALT: "major" # sourced from superseed
      OP_GETH_DB_ENGINE: "pebble"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # do geth init if datadir is empty
        if [ ! -d "/data/geth" ]; then
            echo "Initializing geth datadir"
            geth init --datadir=/data /data/genesis.json
        else
            echo "geth datadir already initialized, skipping..."
        fi
        exec geth
    restart: always
    volumes:
      - ${DATADIR_PATH}/op-geth:/data
      - $PATH_TO_JWT:/jwt.txt
    env_file: [".env"]
    networks:
      - superseednet
    ports:
      - "6645:8545"
      - "6646:8546"
      - "33393:39393/udp"
      - "33393:39393/tcp"
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.11.2 # version sourced from
    container_name: superseed-op-node
    environment:
      OP_NODE_L1_BEACON: "$ETH_BEACON_URL"
      OP_NODE_L2_ENGINE_RPC: "ws://op-geth:8551"
      OP_NODE_ROLLUP_CONFIG: "/data/rollup.json"
      OP_NODE_L2_ENGINE_AUTH: "/jwt.txt"
      OP_NODE_RPC_ADDR: "0.0.0.0"
      OP_NODE_L1_ETH_RPC: "$ETH_URL"
      OP_NODE_P2P_LISTEN_IP: "0.0.0.0"
      OP_NODE_P2P_LISTEN_TCP_PORT: "9222"
      OP_NODE_P2P_LISTEN_UDP_PORT: "9222"
      OP_NODE_ROLLUP_HALT: "major" # sourced from superseed
      OP_NODE_OVERRIDE_GRANITE: "1726185601" # sourced from superseed
      OP_NODE_OVERRIDE_HOLOCENE: "1736445601" # sourced from superseed
      OP_NODE_P2P_BOOTNODES: "enode://3e905f39a5c084367bbe172453cf6d81b28a49f57064b56b0eb76af75d6eafe3d578605f56c4353328194245453083e1c26e339497f732461d2187d0c4a4474e@35.203.166.40:9222?discport=30301,enode://d25ce99435982b04d60c4b41ba256b84b888626db7bee45a9419382300fbe907359ae5ef250346785bff8d3b9d07cd3e017a27e2ee3cfda3bcbb0ba762ac9674@bootnode.conduit.xyz:0?discport=30301,enode://2d4e7e9d48f4dd4efe9342706dd1b0024681bd4c3300d021f86fc75eab7865d4e0cbec6fbc883f011cfd6a57423e7e2f6e104baad2b744c3cafaec6bc7dc92c1@34.65.43.171:0?discport=30305,enode://9d7a3efefe442351217e73b3a593bcb8efffb55b4807699972145324eab5e6b382152f8d24f6301baebbfb5ecd4127bd3faab2842c04cd432bdf50ba092f6645@34.65.109.126:0?discport=30305" # sourced from superseed
      OP_NODE_P2P_STATIC: "/ip4/35.203.166.40/tcp/9222/p2p/16Uiu2HAkydtwWKfTJVk91zmc4JnBzathYyqLSDtw3RCFW1mwkPMk" # sourced from superseed
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until nc -z -w 5 op-geth  8551; do
            echo "Waiting for geth ..."
            sleep 5
        done
        echo "geth is up"
        exec op-node --syncmode=execution-layer
    depends_on:
      - op-geth
    restart: always
    volumes:
      - ${DATADIR_PATH}/op-node:/data
      - $PATH_TO_JWT:/jwt.txt
    env_file: [".env"]
    networks:
      - superseednet
    ports:
      - "6622:9222/tcp"
      - "6622:9222/udp" 
networks:
  superseednet:
    driver: bridge
```
